import './globals.css';
import { Inter } from 'next/font/google';
import { NextUIProvider, createTheme } from '@nextui-org/react';

const inter = Inter({ subsets: ['latin'] });
const darkTheme = createTheme({ type: 'dark' });

export const metadata = {
  title: 'Landing-Page',
  description: 'Generated by create next app',
};

//@react-server use client;
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextUIProvider theme={darkTheme}>
        <body className={inter.className}>{children}</body>
      </NextUIProvider>
    </html>
  );
}
