import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Landing-Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  const header = (
    <header>
      <div>
        <h1>Welcome to my landing page</h1>
      </div>
    </header>
  )

  const footer = ( 
    <footer>
      <div>
        <p>Developed by Eric</p>
      </div>
    </footer>
  )
  
  return (
    <html lang="en">
      {header}
      <body className={inter.className}>{children}</body>
      {footer}
    </html>
  )
}
